### ISSUE TITLE
todos and isLoggedIn signals are shared between users

### ISSUE THREAD

**Issue by kt3k** [iuioiua/fresh-saas-toolkit#1]
Steps to reproduce the issue.

- Sign in as User A
- Create some todo list
- In different browser (or different browser profile), visit `/todos`
- Then you can see todo list of A as anonymous user

The `todos` signal seems created only once for deployment in server side. I think we shouldn't use signals on server side code (signals only make sense for communicating client side components in my view)

**Comment by kt3k** [comment]
todos and isLoggedIn are per-user concepts. So they should be stored in `ctx.state` instead of server global signal.

**Comment by iuioiua** [comment]
Thanks, Yoshiya. Will fix 👍🏾

**Comment by thorwebdev** [comment]
In case useful, I've started working on an example with supabase auth here: https://github.com/thorwebdev/everydaylytics

There's a couple important components:

1. Implementation of cookies as auth storage: https://github.com/thorwebdev/everydaylytics/blob/main/components/supabase.ts#L8-L35 (I'm considering pulling this out into an [auth-helpers](https://github.com/supabase/auth-helpers) package)
2. Auth api: https://github.com/thorwebdev/everydaylytics/blob/main/routes/api/auth/%5Bauth%5D.ts
3. Getting auth state and querying with RLS inside a handler: https://github.com/thorwebdev/everydaylytics/blob/main/routes/index.tsx#L9-L15

**Comment by iuioiua** [comment]
Thanks, @thorwebdev! Very good pointers.

**Comment by iuioiua** [comment]
@kt3k, I've removed the use of signals in todos. Please test again.

**Comment by kt3k** [comment]
Confirmed it's fixed now. Great!

But `isLoggedIn` signal still seems shared between requests. (It's set in `_middleware.ts` and that signal only exists per server. So the next request could overwrite `isLoggedIn.value`. I think we need to set that value in `ctx.state`, instead of signal.

**Comment by iuioiua** [comment]
Sorry, I should've been clear. I'll have `isLoggedIn` done soon.

**Comment by iuioiua** [comment]
This has now been fixed around the codebase. Do you have any other concerns regarding this issue, @kt3k?

**Comment by kt3k** [comment]
This now looks good to me. Thanks for updating!
