### ISSUE TITLE
replace all demo logos

### ISSUE THREAD

**Issue by lambtron** [iuioiua/fresh-saas-toolkit#4]
let's replace all of these:

![image](https://user-images.githubusercontent.com/1080190/223869860-29ab96fc-de96-4898-8f6f-ea19994d67be.png)

with these:

![saaskit-logo-round-transparent](https://user-images.githubusercontent.com/1080190/223869896-046b4e7c-4c97-4aa4-b5a6-54233ff5d67a.png)

**Comment by iuioiua** [comment]
The only place this appears is the favicon, which has now been replaced.
