### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by lambtron** [iuioiua/fresh-saas-toolkit#7]
i can take this one.

basically make the readme very thorough and cover:
- what this is (marketing copy)
- how to get started/setup
- links to deno.com/blog, deno.com/saaskit, relevant youtube videos, discord if they're stuck
- direct users to issues for feedback

**Comment by iuioiua** [comment]
Are we able to transfer this issue to the new repo?

**Comment by iuioiua** [comment]
Closed in favour of duplicate issue in new repo.
